"""admin_dashboard_fields

Revision ID: 1e36f5716307
Revises: fad49e425935
Create Date: 2026-09-17 18:05:14.483217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e36f5716307'
down_revision: Union[str, None] = 'fad49e425935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(), server_default='api', nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('jobs', 'source')
    op.drop_column('api_keys', 'revoked_at')
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'created_at')
    # ### end Alembic commands ###
