"""add chats table

Revision ID: b3301b167d01
Revises: aaa111bbb222
Create Date: 2026-09-17 13:05:38.149861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3301b167d01'
down_revision: Union[str, None] = 'aaa111bbb222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('chat_id', sa.UUID(), nullable=True))
    op.drop_index('ix_jobs_user_id_created_at_desc', table_name='jobs')
    op.create_index(op.f('ix_jobs_chat_id'), 'jobs', ['chat_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_chat_id'), table_name='jobs')
    op.create_index('ix_jobs_user_id_created_at_desc', 'jobs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.drop_column('jobs', 'chat_id')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
