"""add_clerk_id

Revision ID: ee755d08aa64
Revises: 1e36f5716307
Create Date: 2026-09-17 18:23:53.211353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee755d08aa64'
down_revision: Union[str, None] = '1e36f5716307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###
